// import React from "react";

export { default as Day1 } from "./Day1/Day1";
export { default as Day2 } from "./Day2/Day2";
export { default as Day3 } from "./Day3/Day3";
export { default as Day4 } from "./Day4/Day4";
export { default as Day5 } from "./Day5/Day5";
export { default as Day6 } from "./Day6/Day6";
export { default as Day7 } from "./Day7/Day7";
export { default as Day8 } from "./Day8/Day8";
export { default as Day9 } from "./Day9/Day9";
export { default as Day10 } from "./Day10/Day10";
export { default as Day11 } from "./Day11/Day11";
export { default as Day12 } from "./Day12/Day12";
export { default as Day13 } from "./Day13/Day13";
export { default as Day14 } from "./Day14/Day14";
export { default as Day15 } from "./Day15/Day15";
export { default as Day16 } from "./Day16/Day16";
export { default as Day17 } from "./Day17/Day17";
export { default as Day18 } from "./Day18/Day18";
export { default as Day19 } from "./Day19/Day19";
export { default as Day20 } from "./Day20/Day20";
export { default as Day21 } from "./Day21/Day21";
export { default as Day22 } from "./Day22/Day22";
export { default as Day23 } from "./Day23/Day23";
export { default as Day24 } from "./Day24/Day24";
export { default as Day25 } from "./Day25/Day25";
export { default as Questions } from "./Questions/Questions";